name: demo_app
description: "Netrofit Demo - Countries Explorer"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # Netrofit - All-in-one package
  netrofit_all:
    path: ../packages/netrofit_all
  json_annotation: ^4.9.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.8
  get_it: ^9.2.0
  google_fonts: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  
  # Code generation
  netrofit_generator:
    path: ../packages/netrofit_generator
  build_runner: ^2.4.0
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
